app/users/models.py
from app import bcrypt, db


class User(db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(60), nullable=False)

    def __repr__(self):
        return f"User('{self.email}')"

    def hash_password(self, password):
        return bcrypt.generate_password_hash(password).decode("utf-8")

    def check_password(self, password):
        return bcrypt.check_password_hash(self.password, password)

app/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, Length, ValidationError, Regexp

from app.users.models import User


class RegistrationForm(FlaskForm):
    username = StringField("Username",
                           validators=[
                               DataRequired(),
                               Length(min=3, max=20),
                               Regexp("^[A-Za-z0-9_]+$",
                                      message="Username must contain only letters, numbers, and underscores.")
                           ])

    email = StringField("Email",
                        validators=[
                            DataRequired(),
                            Email()
                        ])

    password = PasswordField("Password",
                             validators=[
                                 DataRequired(),
                                 Length(min=8, max=128, message="Password must be between 8 and 128 characters.")
                             ])

    confirm_password = PasswordField("Confirm Password",
                                     validators=[
                                         DataRequired(),
                                         EqualTo("password", message="Passwords must match.")
                                     ])

    submit = SubmitField("Register")

    def validate_email(self, email):
        user = User.query.filter_by(username=email.data).first()
        if user:
            raise ValidationError("This email is already registered.")

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError("This username is already taken.")

app/users/__init__.py
from flask import Blueprint

users_blueprint = Blueprint("users", __name__,  url_prefix="/users", template_folder="templates", static_folder="static")

from . import views

app/users/views.py
from datetime import timedelta

from flask import (render_template,
                   request,
                   url_for,
                   redirect,
                   flash,
                   session,
                   make_response)

from app import bcrypt, db
from . import users_blueprint
from .forms import RegistrationForm
from .models import User


@users_blueprint.route('/hi/<string:name>')
def greetings(name):
    name = name.upper()
    age = request.args.get("age", type=int)
    return render_template("hi.html", name=name, age=age)


@users_blueprint.route("/admin")
def admin():
    to_url = url_for("users.greetings", name="administrator",
                     age=19, _external=True)
    return redirect(to_url)


@users_blueprint.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")

        user = User.query.filter_by(username=username).first()

        if user and user.check_password(password):
            session["username"] = user.username
            session["email"] = user.email

            flash("Login successful!", "success")
            return redirect(url_for("users.account"))
        else:
            flash("Invalid username or password", "danger")
    return render_template("login.html")


@users_blueprint.route("/profile", methods=["GET", "POST"])
def profile():
    if "username" not in session:
        flash("You need to log in to view this page.", "warning")
        return redirect(url_for("users.login"))

    if request.method == "POST":
        action = request.form.get("action")

        if action == "add":
            key = request.form.get("key")
            value = request.form.get("value")
            days = request.form.get("days", type=int)

            if key and value and days:
                response = make_response(redirect(url_for("users.profile")))
                response.set_cookie(key, value, max_age=timedelta(days=days))
                flash(f"Cookie '{key}' added successfully!", "success")
                return response
            else:
                flash_message = (
                        "Please provide a valid key, "
                        "value and expiration days."
                )
                flash(flash_message, "danger")
        elif action == "delete_key":
            key = request.form.get("delete_key")
            response = make_response(redirect(url_for("users.profile")))
            response.set_cookie(key, "", expires=0)
            flash(f"Cookie '{key}' deleted successfully!", "success")
            return response

        elif action == "delete_all":
            response = make_response(redirect(url_for("users.profile")))
            for cookie_key in request.cookies.keys():
                response.set_cookie(cookie_key, "", expires=0)
            flash("All cookies deleted successfully!", "success")
            return response

    current_cookies = request.cookies.to_dict()
    return render_template("profile.html", username=session["username"],
                           cookies=current_cookies)


@users_blueprint.route("/logout", methods=["POST"])
def logout():
    session.pop("username", None)
    flash("You have benn logged out.", "info")
    return redirect(url_for("users.login"))


@users_blueprint.route("/set_color_scheme/<string:scheme>")
def set_color_scheme(scheme):
    if scheme not in ["light", "dark"]:
        flash("Invalid color scheme selected.", "danger")
        return redirect(url_for("users.profile"))

    response = make_response(redirect(url_for("users.profile")))
    response.set_cookie("color_scheme", scheme, max_age=timedelta(days=30))
    flash(f"Color scheme set to {scheme.capitalize()}!", "success")
    return response


@users_blueprint.route("/sign-up", methods=["GET", "POST"])
def signup():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode("UTF-8")
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash("Your account has benn created! You can now log in.", "success")
        return redirect(url_for("users.login"))
    return render_template("register.html", title="Register", form=form)


@users_blueprint.route("/account")
def account():
    if "username" not in session:
        flash("You must log in to view this page.", "warning")
        return redirect(url_for("users.login"))

    username = session.get("username")
    email = session.get("email")

    return render_template("account.html", username=username, email=email)

app/users/templates/account.html
{% extends 'base.html' %}

{% block content %}
<div class="profile">
    <h2>Профіль користувача</h2>
    <p><strong>Ім'я користувача:</strong> {{ username }}</p>
    <p><strong>Email:</strong> {{ email }}</p>
    <form action="{{ url_for('users.logout') }}" method="POST">
      <button type="submit" class="btn btn-danger">Вийти</button>
    </form>
</div>
{% endblock %}

app/users/templates/hi.html
{% extends "base.html" %}

{% block content %}
    <h1>Hello =) </h1>

    {% if name %}
        <p style="color: green;">Ім'я: {{ name }}</p>
    {% else %}
        <p style="color: red;">Name not provided</p>
    {% endif %}

    {% if age is not none %}
        <p style="color: green;">Вік: {{ age }}</p>
    {% else %}
        <p style="color: red;">Age not provided</p>
    {% endif %}
{% endblock %}

app/users/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="login-container">
    <h2>Вхід до системи</h2>
    <form action="{{ url_for('users.login') }}" method="post">
        <label for="username">Ім'я користувача:</label>
        <input type="text" id="username" name="username" required>

        <label for="password">Пароль:</label>
        <input type="password" id="password" name="password" required>

        <button type="submit" class="login-button">Увійти</button>
    </form>
</div>
{% endblock %}

app/users/templates/profile.html
{% extends "base.html" %}

{% block content %}
<div class="profile-container {% if request.cookies.get('color_scheme') == 'dark' %}dark-theme{% else %}light-theme{% endif %}">
    <h2>Вітаємо, {{ username }}!</h2>
    <p>Ви увійшли до системи.</p>

    <div class="color-scheme-buttons">
        <a href="{{ url_for('users.set_color_scheme', scheme='light') }}" class="btn">Світла тема</a>
        <a href="{{ url_for('users.set_color_scheme', scheme='dark') }}" class="btn">Темна тема</a>
    </div>

    <h3>Керування куками</h3>
    
    <form action="{{ url_for('users.profile') }}" method="post">
        <input type="hidden" name="action" value="add">
        <label for="key">Ключ:</label>
        <input type="text" id="key" name="key" required>

        <label for="value">Значення:</label>
        <input type="text" id="value" name="value" required>

        <label for="days">Термін дії (днів):</label>
        <input type="number" id="days" name="days" min="1" required>

        <button type="submit">Додати куку</button>
    </form>

    <form action="{{ url_for('users.profile') }}" method="post">
        <input type="hidden" name="action" value="delete_key">
        <label for="delete_key">Видалити куку за ключем:</label>
        <input type="text" id="delete_key" name="delete_key" required>
        <button type="submit">Видалити куку</button>
    </form>

    <form action="{{ url_for('users.profile') }}" method="post">
        <input type="hidden" name="action" value="delete_all">
        <button type="submit">Видалити всі куки</button>
    </form>

    <h3>Поточні куки</h3>
    <table>
        <thead>
            <tr>
                <th>Ключ</th>
                <th>Значення</th>
            </tr>
        </thead>
        <tbody>
            {% for key, value in cookies.items() %}
            <tr>
                <td>{{ key }}</td>
                <td>{{ value }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

app/users/templates/register.html
{% extends "base.html" %}

{% block css %}
  <link rel="stylesheet" href="{{ url_for('users.static', filename='css/style.css') }}">
{% endblock css %}

{% block content %}
<h1>Реєстрація</h1>
<form method="POST">
    {{ form.hidden_tag() }}
    <div>
        {{ form.username.label }}<br>
        {{ form.username(size=20) }}<br>
        {% for error in form.username.errors %}
            <small>{{ error }}</small>
        {% endfor %}
    </div>
    <div>
        {{ form.email.label }}<br>
        {{ form.email(size=20) }}<br>
        {% for error in form.email.errors %}
            <small>{{ error }}</small>
        {% endfor %}
    </div>
    <div>
        {{ form.password.label }}<br>
        {{ form.password(size=20) }}<br>
        {% for error in form.password.errors %}
            <small>{{ error }}</small>
        {% endfor %}
    </div>
    <div>
        {{ form.confirm_password.label }}<br>
        {{ form.confirm_password(size=20) }}<br>
        {% for error in form.confirm_password.errors %}
            <small>{{ error }}</small>
        {% endfor %}
    </div>
    <div>
        {{ form.submit() }}
    </div>
</form>
{% endblock content %}